hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("notify-usb")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store -max-dedupe-search 10 -max-items 100")
	hl.exec_cmd("wl-paste --type image --watch cliphist store -max-dedupe-search 10 -max-items 100")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
	hl.exec_cmd("gnome-keyring-daemon --start --components=secrets,ssh")
	hl.exec_cmd("hyprsunset -t 4800")
	hl.exec_cmd("hyprpm update")
	-- hl.exec_cmd("qs -c noctalia-shell")
end)
