hl.on("hyprland.start", function()
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaync")
	hl.exec_cmd("notify-usb")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("wl-paste --type text --watch cliphist store -max-dedupe-search 10 -max-items 100")
	hl.exec_cmd("wl-paste --type image --watch cliphist store -max-dedupe-search 10 -max-items 100")
	hl.exec_cmd("hyprpaper")
	hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
	hl.exec_cmd("systemctl --user start hyprpolkitagent.service")
	hl.exec_cmd("[workspace special:magic silent] ~/Applications/kanri_0.8.2_amd64.AppImage")
end)
