wallpaper {
    monitor = eDP-1 
    path =  /home/gbesh/Pictures/wallpapers/wallhaven-q6kw6r_1920x1080.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/gbesh/Pictures/wallpapers/wallhaven-ymogyx_1920x1080.png
    fit_mode = cover
}

splash = false
